name: Build

on:
  schedule:
  - cron: "25 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install utils
        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install jq && pip3 install netaddr

      - name: Run our scripts
        id: release
        run: |
          ./1-gen-blocked-ips.sh
          ./2-gen-allowed-ips.sh
          ./3-gen-public-cloud-ranges.py
          ./4-gen-user-agents.sh
          ./5-gen-cdn-ips.sh
          ./6-get-geo-ranges.py
          echo "builddate=$(date -Is)" >> $GITHUB_OUTPUT
          echo "epochdate=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Push changes if updated
        run: git diff --quiet || (git add -A && git commit -m "Update from GitHub Actions" && git pull --rebase && git push)

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: SiteHost NZ
          author_email: support@sitehost.co.nz
          message: "Automatic build date: ${{ steps.release.outputs.builddate }}"
          tag: "${{ steps.release.outputs.epochdate }}"
