name: Build

on:
  schedule:
  - cron: "25 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install utils
        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install jq && pip3 install netaddr

      - name: Run our scripts
        id: release
        run: ./build.sh $(curl -s "https://api.github.com/repos/RiddleCA/ip-ua-data/actions/runs" | jq '.workflow_runs | map(select(.name == "Build" and .conclusion == "success")) | .[0].created_at')

      - name: Push changes if updated
        run: ./git-actions.sh
