name: Build

on:
  schedule:
  - cron: "25 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install utils
        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install jq && pip3 install netaddr
        
      - name: Fetch workflow runs
        id: fetch_runs
        run: RUNS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs") echo "::set-output name=runs::$RUNS"

      - name: Extract timestamp of last successful "build" workflow run
        id: extract_last_build_success
        run: |
          LAST_BUILD_SUCCESS=$(echo "$RUNS" | jq '.workflow_runs | map(select(.name == "Build" and .conclusion == "success")) | .[0].created_at')
          echo "::set-output name=last_build_success::$LAST_BUILD_SUCCESS"

      - name: Run our scripts
        id: release
        run: ./build.sh ${{ steps.extract_last_build_success.outputs.last_build_success }}

      - name: Push changes if updated
        run: git-actions.sh

