name: Expire

on:
  schedule:
  - cron: "25 * * * *"
  workflow_dispatch:

jobs:
  expire:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Remove expired IPs
        run: awk -i inplace -v current_time=$(date +%s) '$2 > current_time' suspiciousips/operations

      - name: Push changes if updated
        run: |
          git config --global user.email "support@sitehost.co.nz"
          git config --global user.name "SiteHost NZ"
          git diff --quiet || (git add -A && git commit -m "Update from GitHub Actions" && git pull --rebase)
        
