name: Expire

on:
  schedule:
  - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  expire:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Remove expired IPs
        run: |
          awk -i inplace -v current_time=$(date +%s) '$2 > current_time' suspiciousips/operations
          echo "builddate=$(date -Is)" >> $GITHUB_OUTPUT
          echo "epochdate=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Commit changes
        run: ./git-actions.sh
